# PlatformIO Configuration File for Aero Hand Open / Custom Hand
# https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = right

[env]
platform = espressif32
board = seeed_xiao_esp32s3
framework = arduino

# シリアルモニターの通信速度を設定 (firmware.ino の Serial.begin(921600) に同期)
monitor_speed = 921600

# 必要な外部ライブラリの自動ダウンロード設定
lib_deps =
    # FEETECHサーボ公式ライブラリをGitHubから直接インポート
    https://github.com/ftservo/FTServo_Arduino.git

[env:right]
build_flags =
    -DRIGHT_HAND

[env:left]
build_flags =
    -DLEFT_HAND