# PlatformIO Configuration File for Aero Hand Open / Custom Hand
# https://docs.platformio.org/page/projectconf.html

[env:seeed_xiao_esp32s3]
platform = espressif32
board = seeed_xiao_esp32s3
framework = arduino

# シリアルモニターの通信速度を設定 (firmware.ino の Serial.begin(921600) に同期)
monitor_speed = 921600

# 必要な外部ライブラリの自動ダウンロード設定
lib_deps =
    # FEETECHサーボ公式ライブラリをGitHubから直接インポート
    https://github.com/ftservo/FTServo_Arduino.git
    

# 必要に応じてビルドフラグを設定可能
# build_flags = 
#     -DRIGHT_HAND
#     -DLEFT_HAND